name: "Video: FinanzasClara"
on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  video:
    uses: ./.github/workflows/video_engine.yml
    with:
      channel: finanzas_clara
    secrets: inherit
