name: "Video: SaludLongevidad"
on:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 11 * * *'
    - cron: '0 14 * * *'
    - cron: '0 17 * * *'
    - cron: '0 20 * * *'
  workflow_dispatch:
jobs:
  video:
    uses: ./.github/workflows/video_engine.yml
    with:
      channel: salud_longevidad
    secrets: inherit
