name: "Video: VidaSana360"
on:
  schedule:
    - cron: '0 8 * * *'
    - cron: '0 16 * * *'
  workflow_dispatch:
jobs:
  video:
    uses: ./.github/workflows/video_engine.yml
    with:
      channel: vida_sana_360
    secrets: inherit
