name: "Video: CashCafe (Shorts)"
on:
  schedule:
    - cron: '0 13 * * *'
    - cron: '0 16 * * *'
    - cron: '0 19 * * *'
    - cron: '0 22 * * *'
  workflow_dispatch:
jobs:
  video:
    permissions:
      contents: write
    uses: ./.github/workflows/video_engine.yml
    with:
      channel: cash_cafe_shorts
    secrets: inherit
