name: "Video: SaludLongevidad"
on:
  schedule:
    - cron: '30 8 * * *'
    - cron: '30 16 * * *'
  workflow_dispatch:
jobs:
  video:
    uses: ./.github/workflows/video_engine.yml
    with:
      channel: salud_longevidad
    secrets: inherit
