name: "Video: CatBrothers"
on:
  schedule:
    - cron: '30 13 * * *'  # 09:30 EST (mañana US)
    - cron: '30 17 * * *'  # 13:30 EST (almuerzo US)
    - cron: '30 23 * * *'  # 19:30 EST (prime time US)
  workflow_dispatch:
jobs:
  video:
    uses: ./.github/workflows/video_engine.yml
    with:
      channel: catbrothers
    secrets: inherit
