name: "Video: CashCafe (Long-Form)"
on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:
jobs:
  video:
    uses: ./.github/workflows/longform_engine.yml
    with:
      channel: cash_cafe
    secrets: inherit
