name: "Video: DisasterDecode"

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  video:
    uses: ./.github/workflows/longform_engine.yml
    with:
      channel: calm_earth
    secrets: inherit
